const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';

const NEW_ATTACHMENT = 'NEW_ATTACHMENT';
const NEW_MESSAGE_ALTER = 'NEW_MESSAGE_ALTER';

export { ALERT, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE_ALTER };